language: go

branches:
  only:
    - master

script:
  - go get github.com/apache/thrift/lib/go/thrift
  - go get github.com/ovr/go-calculate-thrift/gen-go/tutorial
  - go get github.com/stretchr/testify/assert
  - make tests
